// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzomidicqudfzebocftj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6b21pZGljcXVkZnplYm9jZnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDQ3NzYsImV4cCI6MjA3MDgyMDc3Nn0.LUIAS-R-XjVdKeX1YxWB0nIK1g06eXx_X5b_YHhbybs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});